on:
  push:
    branches:
      - '*'
  schedule:
    - cron: '* 1 * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: First step
        run: echo "Halojaa"
      - name: health check
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://own-build-ci-cd.onrender.com/api/health
          max-attempts: 3
          retry-delay: 10s
